apiVersion: apps/v1
kind: Deployment
metadata:
  name: audit-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audit
  template:
    metadata:
      labels:
        app: audit
    spec:
      containers:
      - name: audit
        image: shivaram1918/vibha-audit:latest
        ports:
        - containerPort: 8080
