apiVersion: apps/v1
kind: Deployment
metadata:
  name: loan-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loan
  template:
    metadata:
      labels:
        app: loan
    spec:
      containers:
      - name: loan
        image: shivaram1918/vibha-loan:v3
        ports:
        - containerPort: 8080
